### ISSUE TITLE
frontend: 画面の縦サイズが小さいと古いチャットが見えない

### ISSUE THREAD

**Issue by iorar** [85yago/go_small_chat#38]
ウィンドウサイズの縦方向が小さいと下の方のチャットが見えなくなります
（スクロールバーを下に送っても見えず、『戻る』のリンクと被ってしまう）

多分cssの設定ミスだと思います

![image](https://user-images.githubusercontent.com/57796209/209943583-1f29ba51-0066-42cd-af85-6759fe844f48.png)

**Comment by iorar** [comment]
```chat.css
#message_area {
  overflow: hidden;
  height: 75vh;
}
```
ここの`overflow: hidden`が原因だと思います

**Comment by iorar** [comment]
普通に
```CSS
#message_area {
  overflow: visible;
  height: auto;
}
```
でよくね？となった
